services:
  postgres:
    image: postgres:17.7-alpine
    container_name: loadbalancer-postgres
    environment:
      POSTGRES_DB: lb
      POSTGRES_USER: lb
      POSTGRES_PASSWORD: lb
    ports:
      - "5448:5432"
    volumes:
      - pg-loadbalancer:/var/lib/postgresql/data
volumes:
  pg-loadbalancer: