[versions]
java = "21"

spring-boot = "3.5.9"
lombok = "1.18.42"
apache-compress = "1.28.0"

flyway = "11.20.1"
postgres = "42.7.8"
testcontainers = "1.21.4"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
# Spring Boot BOM (for library module via platform/enforcedPlatform)
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

# Lombok
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

# Starters (no versions here -> controlled by Boot BOM / Boot plugin)
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
apache-compress = { module = "org.apache.commons:commons-compress", version.ref = "apache-compress" }

# Flyway + DB driver
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# Testcontainers
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

# JUnit Platform launcher (often needed explicitly at testRuntimeOnly)
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
